version: '{build}'
image: Visual Studio 2017
before_build:
- cmd: >-
    nuget restore SpeckleCore/SpeckleCore.sln

    mkdir %appdata%\Grasshopper\Libraries\SpeckleSendReceive
build:
  project: SpeckleCore/SpeckleCore.sln
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook:
    secure: 9Kt/ImvGdsQ/dzmRdSaMIG+BO0R29MOJC7eZZnK5m5TyWwE+4nofEcYlb/r4lh9Z1Dx/bR+7oQtgAYO3W5s+qJshkT6Is9irYw3TfMZX7/M=
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
